### ISSUE TITLE
Make the FeatureCard changing its colors two different gradients. 

### ISSUE THREAD

**Issue by supunvindula** [supunvindula/campUS-Web#1]
- You have to branch out from **feature-section** branch. create a PR to that branch after finishing.
- The FeatureCard is located at src/components/FeatureCard.jsx.
- You have to make the background gradient change its color to some colors taken from a matching color array.
- You have to decide the matching colors related to the current color I have inserted on.

![image](https://github.com/supunvindula/campUS-Web/assets/59873941/98cd0acc-f8fb-4e4b-b286-7a33a46652de)

**Comment by Muz4mmil** [comment]
Hello @supunvindula , can you please elaborate the issue?
you want to change the gradient color on some interaction like click or hover? or just want to change this one ??
I can do both. So please kindly clear me the issue and assign it to me

**Comment by supunvindula** [comment]
Hi @Muz4mmil . I need to change gradient colors when the card changes. As you can see the car changes its title and description for every 2 seconds. So with that i want to change the current gradient to another color pair.

**Comment by Muz4mmil** [comment]
> Hi @Muz4mmil . I need to change gradient colors when the card changes. As you can see the car changes its title and description for every 2 seconds. So with that i want to change the current gradient to another color pair.

Got it, thanks for explanation. Assign me the task and i'll try to complete. Also, please add other hacktoberfest tags like "hacktoberfest-accepted" because i got some issues on my previous contributions. just a request.

**Comment by supunvindula** [comment]
I have assigned you for this task. Please go ahead @Muz4mmil

**Comment by Muz4mmil** [comment]
> I have assigned you for this task. Please go ahead @Muz4mmil

Thanks. One more thing, will you suggest some gradients or should i choose according to the website theme and accent?

**Comment by supunvindula** [comment]
Go with the website theme and colors looks same like the color gradient now. You can decide

**Comment by supunvindula** [comment]
@Muz4mmil Hi any update?

**Comment by Muz4mmil** [comment]
> @Muz4mmil Hi any update?

Hello @supunvindula , I am extremely sorry for delay in the completion of the task. As I have my university exams, the schedule is a bit tight. 
The issue won't take long time to fix i guess and Will surely complete it in a couple of days.

**Comment by supunvindula** [comment]
It is fine @Muz4mmil , But keep in mnd that for hacktoberfest you have to create PRs before the October month ends. Just 3 days to do the tasks. Good luck for your exams btw!!

**Comment by Muz4mmil** [comment]
Hey @supunvindula 
I completed the work. Kindly check and Merge it under hacktoberfest.
And thanks for waiting.

**Comment by Muz4mmil** [comment]
Hey @supunvindula
I guess we missed something. or I created a new issue by mistake which got merged.
Because this one is not getting counted in hacktoberfest.
It says 'Not-Participating' in hacktoberfest page

Can you please try adding tags and labels of `hacktoberfest` and `hacktoberfest-accepted` to this issue?
Thanks

**Comment by supunvindula** [comment]
Issue closed in #2
